name: CI - Indexer job (deploy if master branch)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - if: github.ref != 'refs/heads/master' || github.repository_owner != 'betaflight' 
      name: Run the checker script
      run: ./scripts/build.sh

    - if: github.ref == 'refs/heads/master' && github.repository_owner == 'betaflight' 
      name: Run the checker, indexer and deployment script
      run: ./scripts/build.sh deploy

    - if: github.ref == 'refs/heads/master' && github.repository_owner == 'betaflight' 
      name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: public
        retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'betaflight' 
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v5
      with:
        name: dist-files
        path: public
          
    - name: Set alias branch name for Cloudflare (if a push)
      id: branch_push
      run: |
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Deploy to Cloudflare
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy public --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=${{ env.BRANCH }} --commit-dirty=true
